import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { getLast5Days } from '../hooks/getLast5Days';
import ImageGrid from '../components/frontPageRange';

export default function Home() {
  const [pictureData, setPictureData] = useState([]);

  useEffect(() => {
    async function getData() {
      const response = await getLast5Days();
      setPictureData(response);
    }
    getData();
  }, []);

  if (!pictureData.length > 0) {
    return (
      <div className="flex flex-col items-center justify-center flex-1 px-40 text-center w-screen h-screen">
        <h1 className="text-6xl text-lightPurple font-bold mb-20">
          Loading...
        </h1>
        <Image
          src="https://i.imgur.com/OTBEvfy.gif"
          width={150}
          height={150}
          quality={1}
          alt="Loading animation"
        />
      </div>
    );
  }

  return (
    <div className="backgroundImage flex flex-col items-center justify-center min-h-screen w-screen py-2 overflow-hidden">
      <Head>
        <title>Spacestagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center flex-1 px-10 text-center min-w-screen w-full font-ubuntu mb-10">
        <h1 className="text-6xl text-lightPurple font-bold my-5">
          Spacestagram
        </h1>
        <h2 className="text-2xl text-lightBlue">
          Brought to you by NASA Image API
        </h2>

        <ImageGrid pictureData={pictureData} />
      </main>

      <footer className=""></footer>
    </div>
  );
}
